#! /usr/bin/rake
#
# Rake file for building qtlHD binaries, libraries and unit tests. 
#
# Examples:
#
#   rake                 # default build and test
#   rake -T              # list all defined rake tasks
#   rake clean
#   rake build          
#   rake run
#   rake test
#   rake csv2xgap        # build utility
#   rake read_csv        # CSV unit tests
#   rake read_csvr       # CSVr unit tests
#   etc. etc. (see rake -T).

require 'rake/clean'

PROG = 'read_csv'  # this will change 
BINARIES = [PROG, :csv2xgap ]
TESTS = [ 'read_csv' ]

core_dfiles_list = Dir.glob("./qtl/core/*.d")
core_dfiles = core_dfiles_list.join(' ')

core_iofiles_list = Dir.glob("./qtl/plugins/input/*.d")
core_iofiles = core_iofiles_list.join(' ')

core_xgap_list = Dir.glob("./qtl/core/xgap/*.d")
core_xgapfiles = core_xgap_list.join(' ')

CLEAN.include('*.o')
CLEAN.include('test.*')
CLEAN.include(%w[ csv2xgap read_csv read_csvr test.xbin write_xgapbin])

# The compile targets

file "read_csv" => core_dfiles_list do
  sh "dmd -unittest -ofread_csv #{core_dfiles} qtl/plugins/input/read_interface.d qtl/plugins/input/read_csv.d test/main.d"
end

file "read_csvr" => core_dfiles_list do
  sh "dmd -unittest -ofread_csvr #{core_dfiles} qtl/plugins/input/read_interface.d qtl/plugins/input/read_csvr.d qtl/plugins/input/read_csv.d test/main.d"
end

file "write_xgapbin" => core_dfiles_list do
  sh "dmd -unittest -ofwrite_xgapbin #{core_dfiles} #{core_iofiles} #{core_xgapfiles} qtl/plugins/output/write_xgapbin.d test/main.d"
end

file "read_xgapbin" => core_dfiles_list do
  sh "dmd -unittest -ofread_xgapbin #{core_dfiles} #{core_iofiles} #{core_xgapfiles} qtl/plugins/output/write_xgapbin.d test/main.d"
end

file "csv2xgap" => core_dfiles_list do
  sh "dmd -ofcsv2xgap #{core_dfiles} #{core_iofiles} #{core_xgapfiles} qtl/util/csv2xgap.d qtl/plugins/output/write_xgapbin.d"
end

# ---- Standard tasks

desc "Default builds and tests #{PROG}"
task :default => [:build, :test]

desc "Build default binaries"
task :build => TESTS

desc "Run #{PROG}"
task :run => [PROG] do
  print "Running #{PROG}\n"
  sh "./#{PROG}" 
end

desc "Test #{PROG}"
task :test => [PROG] do
  print "Testing #{PROG}\n"
  sh "./#{PROG}" 
end

# ---- Utilities


# ---- Unit tests

desc "Test CSVr"
task :test_csvr => [ 'read_csvr' ] do 
  sh "./read_csvr" 
end

desc "Test XGAP"
task :test_xgap => [ 'write_xgapbin', 'read_xgapbin' ] do 
  sh "./write_xgapbin"
  sh "./read_xgapbin"
end

desc "Test all"
task :test_all => [ :test_csvr, :test_xgap ] do 
  sh "./read_csv"
end

