#! /usr/bin/rake
#
# Rake file for building qtlHD binaries, libraries and unit tests. 
#
# Examples:
#
#   rake                 # default build and test
#   rake -T              # list all defined rake tasks
#   rake clean
#   rake build          
#   rake run
#   rake test
#   rake DEBUG=TRUE csv2xgap  # build utility with debug information
#   rake read_csv             # CSV unit tests
#   rake DEBUG=TRUE read_csvr # CSVr unit tests with debug information
#   etc. etc. (see rake -T).

require 'rake/clean'

PROG = 'read_qtab'  # this will change to a utility
BINARIES = [PROG]
TESTS = [ :test_qtab ]

D_TEST  = "-unittest"
d_test  = D_TEST
debug   = false
D_DEBUG = "-gc -debug"
d_debug = ""

if ARGV.index("DEBUG=TRUE")
  debug = true
  d_debug = D_DEBUG
  print "Adding debug information!\n"
end
core_dfiles = Dir.glob("./qtl/core/*.d") + Dir.glob("./qtl/core/map/*.d") + 
              Dir.glob(".qtl/core/hmm/*.d") + Dir.glob("./qtl/core/util/*.d")
deprecated_dfiles = Dir.glob("./qtl/core/deprecate/*.d") + 
  Dir.glob("./qtl/plugins/deprecate/*.d")
lib_dfiles = Dir.glob("./qtl/core/libs/*.d")
csv_dfiles = Dir.glob("./qtl/plugins/csv/*.d")
csvr_dfiles = Dir.glob("./qtl/plugins/csvr/*.d")
qtab_dfiles = Dir.glob("./qtl/plugins/qtab/*.d")
xgap_dfiles = Dir.glob("./qtl/plugins/xgap/*.d")
renv_dfiles = Dir.glob("./qtl/plugins/renv/*.d")
scanone_dfiles = Dir.glob("./qtl/core/scanone/*.d")
mqm_dfiles = Dir.glob("./qtl/core/mqm/*.d")
core_dfiles += deprecated_dfiles;
all_dfiles = core_dfiles + lib_dfiles + csv_dfiles + csvr_dfiles + qtab_dfiles + 
             xgap_dfiles 

def suffix
  if windows? then
    return "dll"
  else
    return "so"
  end
end

def prefix
  if windows? then
    return ""
  else
    return "lib"
  end
end

def windows?
  return RUBY_PLATFORM =~ /(:?mswin|mingw)/
end

#Unix files
CLEAN.include('*.o')
CLEAN.include('*.dep')
CLEAN.include('*.deps')
#Win32 files
CLEAN.include('*.obj','*.exe','*.map')
CLEAN.include('test.*', '*.xbin')
#Created test executabels
clean_exe_list = Dir.glob("*").find_all { |fn| File.executable?(fn) and !File.directory?(fn) }
CLEAN.include(clean_exe_list)

# The compile targets

exe_list = { 
  'read_csv' => { :path => './qtl/plugins/csv', :list => core_dfiles + csv_dfiles },
  'read_csvr' => { :path => './qtl/plugins/csvr', :list => core_dfiles + csvr_dfiles },
  'read_qtab' => { :path => './qtl/plugins/qtab', :list => core_dfiles + qtab_dfiles + all_dfiles },
  'write_qtab' => { :path => './qtl/plugins/qtab', :list => core_dfiles + qtab_dfiles + all_dfiles },
  'read_xgapbin' => { :path => './qtl/plugins/xgap', :list => core_dfiles + xgap_dfiles + csvr_dfiles },
  'write_xgapbin' => { :path => './qtl/plugins/xgap', :list => core_dfiles + xgap_dfiles + csvr_dfiles },
  'test_scanone' => { :path => './test/scanone', :list => core_dfiles + scanone_dfiles },
  'test_mqmscan' => { :path => './test/mqm', :list => core_dfiles + mqm_dfiles + renv_dfiles},
}

exe_list.each do | fn, attr | 
  path = attr[:path]
  list = attr[:list]
  source = path + '/' + fn + '.d'
  list << source 
  list.uniq!

  if fn =~ /test/i
    desc fn
  else
    desc "Test "+fn
  end
  file fn => list do
    if windows?
      sh "dmd #{d_debug} #{d_test} -of#{fn} #{list.join(' ')} #{lib_dfiles.join(' ')} test/main.d"
    else
      sh "dmd #{d_debug} #{d_test} -of#{fn} #{list.join(' ')} test/main.d"
    end
    if debug
      print "RUNNING the debugger, to continue the test, type 'run'\n"
      sh 'gdb '+fn
    else
      sh './'+fn
    end
  end
end

file "csv2xgap" => core_dfiles do
  sh "dmd -ofcsv2xgap #{core_dfiles} #{core_iofiles} #{core_xgapfiles} qtl/util/csv2xgap.d qtl/plugins/xgap/write_xgapbin.d"
end

# ---- Standard tasks

desc "Default builds and tests #{PROG}"
task :default => [:build, :test]

desc "Build default binaries"
task :build => TESTS

desc "Create tags (exurberant tags)"
task :tags => [] do
  print "Creating tags!"
  list = all_dfiles 
  sh "dmd -c -Xftags.json #{list.join(' ')} test/main.d"
  sh "rdmd ../../scripts/d2tags . > tags"
end

desc "Run #{PROG}"
task :run => [PROG] do
  print "Running #{PROG}\n"
  sh "./#{PROG}" 
end

desc "Test #{PROG}"
task :test => [PROG] do
  print "Testing #{PROG}\n"
  sh "./#{PROG}" 
end

# ---- Unit tests

desc "Test XGAP"
task :test_xgap => [ 'write_xgapbin', 'read_xgapbin' ] do 
  sh "./write_xgapbin"
  sh "./read_xgapbin"
end

desc "Test qtlHD qtab"
task :test_qtab => [ 'read_qtab', 'write_qtab' ] do
  sh "./write_qtab" 
  sh "./read_qtab" 
end

desc "Test CSV"
task :test_csv => [ :read_csv ]

desc "Test CSVr"
task :test_csvr => [ :read_csvr ]

desc "Test all"
task :test_all => [:clean, :test_csv, :test_csvr, :test_xgap, :test_qtab ]

