#! /usr/bin/rake
#
# Rake file for building qtlHD binaries, libraries and unit tests. 
#
# Examples:
#
#   rake                 # default build and test
#   rake -T              # list all defined rake tasks
#   rake build          
#   rake run
#   rake test
#   rake csv2xgap        # build utility
#   rake read_csv        # CSV unit tests
#   rake read_csvr       # CSVr unit tests

require 'rake/clean'

PROG = 'read_csv'  # this will change 
BINARIES = [PROG, :csv2xgap ]
TESTS = [ 'read_csv' ]

core_dfiles_list = Dir.glob("./qtl/core/*.d")
core_dfiles = core_dfiles_list.join(' ')

CLEAN.include('*.o')
CLEAN.include('test.*')
CLEAN.include(%w[ csv2xgap read_csv read_csvr test.xbin write_xgapbin])


file "read_csv" => core_dfiles_list do
  sh "dmd -unittest -ofread_csv #{core_dfiles} qtl/plugins/input/read_csv.d test/main.d"
end

file "read_csvr" => core_dfiles_list do
  sh "dmd -unittest -ofread_csvr #{core_dfiles} qtl/plugins/input/read_csvr.d qtl/plugins/input/read_csv.d test/main.d"
end

file "write_xgapbin" => core_dfiles_list do
  sh "dmd -unittest -ofwrite_xgapbin #{core_dfiles} qtl/plugins/output/write_xgapbin.d qtl/plugins/input/read_csv.d qtl/plugins/input/read_csvr.d test/main.d"
end

file "csv2xgap" => core_dfiles_list + ["qtl/util/csv2xgap.d"] do
  sh "dmd -ofcsv2xgap #{core_dfiles} qtl/plugins/output/write_xgapbin.d qtl/plugins/input/read_csv.d qtl/plugins/input/read_csvr.d"
end

# ---- Standard tasks

desc "Default builds and tests #{PROG}"
task :default => [:build, :test]

desc "Build default binaries"
task :build => TESTS

desc "Run #{PROG}"
task :run => [PROG] do
  print "Running #{PROG}\n"
  sh "./#{PROG}" 
end

desc "Test #{PROG}"
task :test => [PROG] do
  print "Testing #{PROG}\n"
  sh "./#{PROG}" 
end

# ---- Utilities


# ---- Unit tests

desc "Test CSVr"
task :test_csvr => [ 'read_csvr' ] do 
  sh "./read_csvr" 
end

desc "Test XGAP"
task :test_xgap => [ 'write_xgapbin' ] do 
  sh "./write_xgapbin" 
end

desc "Test all"
task :test_all => [ :read_csvr, :write_xgapbin, :read_csv ] do 
  sh "./read_csv"
  sh "./read_csvr" 
  sh "./write_xgapbin" 
end

