#! /usr/bin/rake
#
# Rake file for building binaries, libraries and unit tests. 
# Big Thanks to Pjotr Prins for showing me Rake

require 'rake/clean'

LIBS =  ['libraries:mqm']

def builddir;return "build";end

def windows?;return RUBY_PLATFORM =~ /(:?mswin|mingw)/;end

def execext
  if windows? then
    return "exe"
  else
    return "bin"
  end
end
  
CLEAN.include("#{builddir}*.*")
CLEAN.include("#{builddir}")
CLEAN.include("*.#{execext}")
CLEAN.include("*.o")
CLEAN.include("*.dll")
CLEAN.include("*.a")

mqm_files = (Dir.glob("MQM/*.cpp") + Dir.glob("MQM/*.c")).join(' ')

directory builddir

def suffix
  if windows? then
    return "dll"
  else
    return "so"
  end
end

def prefix
  if windows? then
    return ""
  else
    return "lib"
  end
end

def compilerflags
  if windows? then
    return "-lR -lstdc++"
  else
    return "-fPIC"
  end
end

# ---- Standard Libs ----
namespace :libraries do
  desc "Build all libraries"
  task :all => LIBS
  
  desc "The library with mqm functionality"
  task "mqm" do
    compileflags = `R CMD config --cppflags`
    linkflags = `R CMD config --ldflags`
    #raise("R not found on your path") if(!compileflags)
    #raise("R not found on your path") if(!linkflags)
    sh "gcc -shared -o #{prefix}mqm.#{suffix} -DBUILD_DLL #{mqm_files} #{compilerflags.chomp()} #{compileflags.chomp()} #{linkflags} "
    sh "cp #{prefix}mqm.#{suffix} ../D/"
  end
end

# ---- Default task ----

desc "Default is to build all applications"
task :default => 'libraries:all' do
  print "CPP Librarie building OK\n"
end
